### ISSUE TITLE
Support for Gentoo and Sabayon Wikis

### ISSUE THREAD

**Issue by fusion809** [aquach/vim-mediawiki-editor#4]
Hi,

I've been trying to edit Gentoo and Sabayon Wikis with your extension but both keep returning errors such as:

``` sh
/Error detected while processing function <SNR>16_MWRead:
line    2:
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/fusion809/.vim/bundle/vim-mediawiki-editor/plugin/mediawiki_editor.py", line 104, in mw_read
    s = site()
  File "/home/fusion809/.vim/bundle/vim-mediawiki-editor/plugin/mediawiki_editor.py", line 67, in site
    text='/w/'))
  File "/usr/lib64/python2.7/site-packages/mwclient/client.py", line 116, in __init__
    self.site_init()
  File "/usr/lib64/python2.7/site-packages/mwclient/client.py", line 124, in site_init
    siprop='general|namespaces', uiprop='groups|rights', retry_on_error=False)
  File "/usr/lib64/python2.7/site-packages/mwclient/client.py", line 204, in api
    info = self.raw_api(action, **kwargs)
  File "/usr/lib64/python2.7/site-packages/mwclient/client.py", line 316, in raw_api
    raise errors.InvalidResponse(res)
mwclient.errors.InvalidResponse: Did not get a valid JSON response from the server. Check that you used the correct hostname. If you did, the server might be wrongly co
nfigured or experience temporary problems.
```

with `g:mediawiki_editor_url` being set manually to wiki.gentoo.org (when prompted), `g:mediawiki_editor_path` being set to / (when prompted). mwclient has been installed on my PC using `sudo pip install mwclient` and vim-mediawiki-editor works fine for the English Wikipedia. 

Thanks for your time,
Brenton

**Comment by tomodachi94** [comment]
@fusion809 8 years later...

I'm unable to reproduce the bug with the Gentoo wiki. It appears the Sabayon Wiki domain is dead. 

Is it possible that this was a network failure issue?

**Comment by fusion809** [comment]
Could be; doesn't matter anyway, I don't use either distros or have much interest editing their Wikis anymore.
